# Generated by Django 2.0.6 on 2018-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_auto_20180617_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='docs2/%Y/%m/%d', verbose_name='Foto do comprovante do cartão'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='docs/%Y/%m/%d', verbose_name='Foto do documento fiscal'),
        ),
    ]
